# Generated by Django 6.0 on 2026-08-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_emp', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=100)),
                ('prenom_emp', models.CharField(db_column='prénom_emp', max_length=100)),
                ('email_emp', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('demandeur', 'Demandeur'), ('chef département', 'Chef de département'), ('acheteur', 'Acheteur'), ('transitaire', 'Transitaire'), ('directeur', 'Directeur')], default='demandeur', max_length=30)),
                ('etat', models.CharField(choices=[('actif', 'Actif'), ('archivé', 'Archivé')], default='actif', max_length=10)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'Employé',
                'managed': True,
            },
        ),
    ]
