# Generated by Django 6.1 on 2026-08-25 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_hash_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_departement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('dot', models.CharField(max_length=30)),
                ('id_chef', models.ForeignKey(blank=True, db_column='id_chef', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='authentication.employe')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'departement',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='id_departement',
            field=models.ForeignKey(blank=True, db_column='id_departement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='authentication.departement'),
        ),
    ]
