# Generated by Django 6.0 on 2026-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_departement_employe_id_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('demandeur', 'Demandeur'), ('chef département', 'Chef de département'), ('acheteur', 'Acheteur'), ('transitaire', 'Transitaire'), ('controleur', 'Contrôleur'), ('directeur', 'Directeur')], default='demandeur', max_length=30),
        ),
    ]
