# Generated by Django 6.1 on 2026-08-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_departement_employe_id_departement'),
        ('demandes', '0005_demandeachat_date_assignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('da_assignee', 'DA assignée'), ('da_approuvee', 'DA approuvée'), ('da_refusee', 'DA refusée'), ('bc_disponible', 'BC disponible'), ('bc_pris_en_charge', 'BC pris en charge'), ('lc_creee', 'Lettre de crédit créée'), ('dedouanement', 'Dédouanement'), ('livraison', 'Livraison')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='demandes.demandeachat')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.employe')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
