# Generated by Django 6.1 on 2026-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('da_assignee', 'DA assignée'), ('da_approuvee', 'DA approuvée'), ('da_refusee', 'DA refusée'), ('bc_disponible', 'BC disponible'), ('bc_pris_en_charge', 'BC pris en charge'), ('lc_creee', 'Lettre de crédit créée'), ('dedouanement', 'Dédouanement'), ('livraison', 'Livraison'), ('dossier_assigne', 'Dossier assigné')], max_length=30),
        ),
    ]
