# Generated by Django 6.0 on 2026-08-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id_da', models.AutoField(primary_key=True, serialize=False)),
                ('numero_da', models.CharField(max_length=30)),
                ('dot', models.CharField(blank=True, max_length=30, null=True)),
                ('date_creation', models.DateField()),
                ('objet', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('assignee', 'Assignée'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20)),
                ('id_demandeur', models.ForeignKey(db_column='id_demandeur', on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='authentication.employe')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'db_table': 'demande_achat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LettreRejet',
            fields=[
                ('id_lrej', models.AutoField(primary_key=True, serialize=False)),
                ('date_rej', models.DateField()),
                ('motif', models.CharField(max_length=500)),
                ('id_acheteur', models.ForeignKey(db_column='id_acheteur', on_delete=django.db.models.deletion.PROTECT, related_name='lettres_rejet', to='authentication.employe')),
                ('id_da', models.ForeignKey(db_column='id_da', on_delete=django.db.models.deletion.CASCADE, related_name='lettres_rejet', to='demandes.demandeachat')),
            ],
            options={
                'verbose_name': 'Lettre de rejet',
                'verbose_name_plural': 'Lettres de rejet',
                'db_table': 'lettre_rejet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneDemandeAchat',
            fields=[
                ('num_ligne_da', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.IntegerField()),
                ('prix_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_da', models.ForeignKey(db_column='id_da', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='demandes.demandeachat')),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_demande', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de demande',
                'verbose_name_plural': 'Lignes de demandes',
                'db_table': 'ligne_demande_achat',
                'managed': True,
            },
        ),
    ]
