# Generated by Django 6.0 on 2026-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_cours', max_length=20),
        ),
    ]
