# Generated by Django 6.0 on 2026-08-14 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('demandes', '0002_alter_demandeachat_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='id_acheteur',
            field=models.ForeignKey(blank=True, db_column='id_acheteur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to='authentication.employe'),
        ),
    ]
