# Generated by Django 6.0 on 2026-08-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_demandeachat_id_acheteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='date_approbation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_rejet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
