# Generated by Django 6.1 on 2026-08-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_demandeachat_date_approbation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='date_assignation',
            field=models.DateTimeField(blank=True, help_text="Date et heure d'assignation de l'acheteur à la demande", null=True),
        ),
    ]
