export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: (id) => `/users/${id}/edit`,
  SUPPLIERS: '/suppliers',
  SUPPLIERS_CREATE: '/suppliers/create',
  SUPPLIERS_EDIT: (id) => `/suppliers/${id}/edit`,
  CATEGORIES: '/categories',
  CATEGORIES_CREATE: '/categories/create',
  CATEGORIES_EDIT: (id) => `/categories/${id}/edit`,
  PRODUCTS: '/products',
  PRODUCTS_CREATE: '/products/create',
  PRODUCTS_EDIT: (id) => `/products/${id}/edit`,
  PURCHASE_ORDERS: '/purchase-orders',
  PURCHASE_ORDERS_CREATE: '/purchase-orders/create',
  PURCHASE_ORDERS_EDIT: (id) => `/purchase-orders/${id}/edit`,
  DELIVERIES: '/deliveries',
  DELIVERIES_CREATE: '/deliveries/create',
  DELIVERIES_EDIT: (id) => `/deliveries/${id}/edit`,
  INVOICES: '/invoices',
  INVOICES_CREATE: '/invoices/create',
  INVOICES_EDIT: (id) => `/invoices/${id}/edit`,
  STOCK: '/stock',
  STOCK_ADJUST: '/stock/adjust',
}
