# Generated by Django 6.0 on 2026-08-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('demandes', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id_bc', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField(db_column='date_création')),
                ('montant', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='brouillon', max_length=20)),
                ('id_acheteur', models.ForeignKey(db_column='id_acheteur', on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='authentication.employe')),
                ('id_da', models.ForeignKey(blank=True, db_column='id_da', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande', to='demandes.demandeachat')),
                ('id_fournisseur', models.ForeignKey(db_column='id_fournisseur', on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='produits.fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'db_table': 'BonDeCommande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneBonDeCommande',
            fields=[
                ('num_ligne_bc', models.BigAutoField(primary_key=True, serialize=False)),
                ('qte', models.BigIntegerField(blank=True, null=True)),
                ('id_bc', models.ForeignKey(db_column='id_bc', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.bondecommande')),
                ('num_produit', models.ForeignKey(db_column='num_produit', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bc', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de bon de commande',
                'verbose_name_plural': 'Lignes de bons de commande',
                'db_table': 'Ligne de BonDeCommande',
                'managed': True,
            },
        ),
    ]
