# Generated by Django 6.0 on 2026-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('commandes', '0001_initial'),
        ('demandes', '0002_alter_demandeachat_statut'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(choices=[('en cours', 'En cours'), ('annulé', 'Annulé')], default='en cours', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bondecommande',
            constraint=models.UniqueConstraint(fields=('id_fournisseur', 'date_creation', 'id_acheteur'), name='unique_bc_fournisseur_jour_acheteur', violation_error_message="Un bon de commande existe déjà pour ce fournisseur aujourd'hui."),
        ),
    ]
