# Generated by Django 6.1 on 2026-09-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_departement_employe_id_departement'),
        ('commandes', '0002_alter_bondecommande_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierImportation',
            fields=[
                ('id_dossier', models.BigAutoField(primary_key=True, serialize=False)),
                ('tarif_douane', models.CharField(blank=True, max_length=100, null=True)),
                ('autorisation_necessaire', models.BooleanField(default=False)),
                ('autorisation_obtenue', models.BooleanField(default=False)),
                ('numero_autorisation', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_expedition', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_chargement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_reception_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a traiter', 'À traiter'), ('en cours', 'En cours'), ('livré', 'Livré')], default='a traiter', max_length=20)),
                ('id_bc', models.OneToOneField(db_column='id_bc', on_delete=django.db.models.deletion.CASCADE, related_name='dossier_importation', to='commandes.bondecommande')),
                ('id_transitaire', models.ForeignKey(blank=True, db_column='id_transitaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_importation', to='authentication.employe')),
            ],
            options={
                'verbose_name': "Dossier d'importation",
                'verbose_name_plural': "Dossiers d'importation",
                'db_table': 'DossierImportation',
                'managed': True,
            },
        ),
    ]
