# Generated by Django 6.0 on 2026-08-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.BigAutoField(db_column='id_catégorie', primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(db_column='nom_catégorie', max_length=100)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'Catégorie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=200)),
                ('adresse_fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_fournisseur', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'Fournisseur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('num_produit', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=200)),
                ('prix_unit', models.FloatField(blank=True, null=True)),
                ('id_categorie', models.ForeignKey(db_column='id_catégorie', on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'Produit',
                'managed': True,
            },
        ),
    ]
