# Generated by Django 6.0 on 2026-08-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='id_categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='id_fournisseur',
            field=models.ForeignKey(blank=True, db_column='id_fournisseur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.fournisseur'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
